import { Router, type IRouter } from "express";
import healthRouter from "./health";
import adminRouter from "./admin";
import categoriesRouter from "./categories";
import productsRouter from "./products";
import couponsRouter from "./coupons";
import deliveryZonesRouter from "./delivery_zones";
import deliveryStreetsRouter from "./delivery_streets";
import deliveryAreasRouter from "./delivery_areas";
import kmDeliveryRouter from "./km_delivery";
import settingsRouter from "./settings";
import notificationSettingsRouter from "./notificationSettings";
import companyProfileRouter from "./companyProfile";
import businessHoursRouter from "./businessHours";
import ordersRouter from "./orders";
import importRouter from "./import";
import paymentsRouter from "./payments";
import financialRouter from "./financial";
import salesDashboardRouter from "./salesDashboard";
import clubeRouter from "./clube";
import clientesRouter from "./clientes";
import presenceRouter from "./presence";
import uploadsRouter from "./uploads";

const router: IRouter = Router();

router.use(healthRouter);
router.use(adminRouter);
router.use(categoriesRouter);
router.use(productsRouter);
router.use(couponsRouter);
router.use(deliveryZonesRouter);
router.use(deliveryStreetsRouter);
router.use(deliveryAreasRouter);
router.use(kmDeliveryRouter);
router.use(settingsRouter);
router.use(notificationSettingsRouter);
router.use(companyProfileRouter);
router.use(businessHoursRouter);
router.use(ordersRouter);
router.use(importRouter);
router.use(paymentsRouter);
router.use(financialRouter);
router.use(salesDashboardRouter);
router.use(clubeRouter);
router.use(clientesRouter);
router.use(presenceRouter);
router.use(uploadsRouter);

export default router;
